base:
  experiment_name: train_NFDP-512x512_res18_ce_coord_NFDP_mynoise
  model_visualization_dir: Unet/models/visualizations/
  root_dir: /home/jingyu/Projects/python/vscode/Jingyu/Landmark/fourthCeph
  val_dataset: test
search_space:
  NUM_BASES:
    cfg_path: MODEL.NUM_BASES
    type: choice
    values:
    - 1
    - 3
sort_by_importance:

