base:
  experiment_name: tv_test-512x512_NFDP_ce_heatmap_test
  model_visualization_dir: Unet/models/visualizations/
  root_dir: /home/jingyu/Projects/python/vscode/Jingyu/Landmark/secondCeph
  val_dataset: test
search_space:
  NUM_BASES:
    cfg_path: MODEL.NUM_BASES
    type: choice
    values:
    - 1
    - 3
    - 5
    - 7
    - 10
    - 15
sort_by_importance:

