DATASET:
  TYPE: 'Dataset_ISBI'
  PRESET:
    ROOT:  '/home/jingyu/Projects/python/vscode/Jingyu/Landmark/secondCeph/data/ISBI2015/'
    ANN:
      - 'Annotations/400_senior'
      - 'Annotations/400_junior'
    TRAIN:
      IMG_PREFIX: 'RawImage/TrainingData'
      AUG:
        SHIFT_FACTOR:
          - 0.15
          - 0.15
        ROT_FACTOR: 30
        SCALE_FACTOR: 0.3
    VAL:
      IMG_PREFIX: 'RawImage/Test1Data'

    TEST:
      IMG_PREFIX: 'RawImage/Test2Data'

    METHOD_TYPE: 'heatmap'


    SIGMA: 10
    NUM_JOINTS: 19
    NUM_JOINTS_BONE: 15
    BONE_INDICES: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16, 17, 18] # 15个
    NUM_JOINTS_SOFT: 4
    SOFT_INDICES: [12, 13, 14, 15] # 4个，见PDF
    RAW_IMAGE_SIZE:
    - 2400
    - 1935
    IMAGE_SIZE:
    - 1024
    - 1024
    HEATMAP_SIZE:
    - 256
    - 256


MODEL:
  TYPE: 'ResFPN'
  IN_CHANNELS: 3
  PRETRAINED: '' # 预训练的地址
  TRY_LOAD: ''
  NUM_LAYERS: 50
  HIDDEN_LIST: -1
  PRETRAINED_RIGHT: true #判断是否预训练，true 或 null

LOSS:
  TYPE: 'MSELoss_softmax'
  MASK_TYPE: 'pow'
  BASENUMBER: 20
  
VALIDATE:
  SHOWNORM: 'minmaxNorm'
  RADII:
  - 2.0
  - 2.5
  - 3.0
  - 4.0
  HEATMAP2COORD: 'heatmap' # if using heatmap, do medical reapair, else coord for simple rapair
  
TRAIN:
  WORLD_SIZE: 2
  BATCH_SIZE: 2

  BEGIN_EPOCH: 0
  END_EPOCH: 2
  
  OPTIMIZER: 'adam'
  LR: 0.001

  LR_SCHEDULE: 
    TYPE: 'linearLR'
    END_FACTOR: 0.01 # for linear
    T_MAX: 100 # for consine
  GRAD_CLIP: 
    ENABLED: true # if not use, just null
    MAX_NORM: 1 # max norm = 1
    NORM_TYPE: 2 # L2 norm

