DATASET:
  TYPE: 'Dataset_ISBI'
  PRESET:
    ROOT:  '/home/jingyu/Projects/python/vscode/Jingyu/Landmark/secondCeph/data/ISBI2015/'
    ANN:
      - 'Annotations/400_senior'
      - 'Annotations/400_junior'
    TRAIN:
      IMG_PREFIX: 'RawImage/TrainingData'
      AUG:
        SHIFT_FACTOR:
          - 0.15
          - 0.15
        ROT_FACTOR: 30
        SCALE_FACTOR: 0.3
    VAL:
      IMG_PREFIX: 'RawImage/Test1Data'

    TEST:
      IMG_PREFIX: 'RawImage/Test2Data'

    METHOD_TYPE: 'coord'


    SIGMA: 10
    NUM_JOINTS: 19
    RAW_IMAGE_SIZE:
    - 2400
    - 1935
    IMAGE_SIZE:
    - 256
    - 256
    HEATMAP_SIZE:
    - 256
    - 256

MODEL:
  TYPE: 'DHDN'
  POINTS_SIGMA: 0.02 # the gauss noise for points after preprocessing of (img, points)

  IN_CHANNELS: 3
  NUM_FEATURES: 2
  NUM_LAYERS: 5

  NUM_NODES_PER_HYPEREDGE: 5
  NUM_PATTERNS: 5
  HIDDEN_DIM: 128

  PRETRAINED: ''
  TRY_LOAD: ''

LOSS:
  TYPE: 'DHDNLoss'
  MASK_TYPE: 'pow'
  BASENUMBER: 20

  BETA: 0.1
  GAMMA: 0.5
  LABMDA: 0.0
  
VALIDATE:
  SHOWNORM: 'minmaxNorm'
  RADII:
  - 2.0
  - 2.5
  - 3.0
  - 4.0
  
TRAIN:
  WORLD_SIZE: 2
  BATCH_SIZE: 8

  BEGIN_EPOCH: 0
  END_EPOCH: 300
  
  OPTIMIZER: 'adam'
  LR: 0.001

  LR_SCHEDULE: 'cosineAnnealingLR'
    END_FACTOR: 0.01 # for linear
    T_MAX: 100 # for consine
  GRAD_CLIP: 
    ENABLED: true # if not use, just null
    MAX_NORM: 1 # max norm = 1
    NORM_TYPE: 2 # L2 norm


