DATASET:
  TYPE: 'Dataset_ISBI'
  PRESET:
    ROOT:  '/home/jingyu/Projects/python/vscode/Jingyu/Landmark/secondCeph/data/ISBI2015/'
    ANN:
      - 'Annotations/400_senior'
      - 'Annotations/400_junior'
    TRAIN:
      IMG_PREFIX: 'RawImage/TrainingData'
      AUG:
        SHIFT_FACTOR:
          - 0.15
          - 0.15
        ROT_FACTOR: 30
        SCALE_FACTOR: 0.3
    VAL:
      IMG_PREFIX: 'RawImage/Test1Data'

    TEST:
      IMG_PREFIX: 'RawImage/Test2Data'

    METHOD_TYPE: 'heatmap' # only heatmap is supported


    SIGMA: 3
    NUM_JOINTS: 19
    RAW_IMAGE_SIZE:
    - 2400
    - 1935
    IMAGE_SIZE:
    - 512
    - 512
    HEATMAP_SIZE:
    - 512
    - 512

MODEL:
  TYPE: 'FARNet'
  IN_CHANNELS: 3
  PRETRAINED: ''
  TRY_LOAD: ''

LOSS:
  TYPE: 'MSELoss_minmaxNorm'
  MASK_TYPE: 'pow'
  BASENUMBER: 40
  
VALIDATE:
  SHOWNORM: 'minmaxNorm'
  RADII:
  - 2.0
  - 2.5
  - 3.0
  - 4.0
  
TRAIN:
  WORLD_SIZE: 2
  BATCH_SIZE: 8
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  OPTIMIZER: 'adam'
  LR: 0.0004
  END_FACTOR: 0.01

