DATASET:
  PRESET:
    ANN:
    - Annotations/400_senior
    - Annotations/400_junior
    BONE_INDICES:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 16
    - 17
    - 18
    HEATMAP_SIZE:
    - 128
    - 128
    IMAGE_SIZE:
    - 512
    - 512
    METHOD_TYPE: heatmap
    NUM_JOINTS: 19
    NUM_JOINTS_BONE: 15
    NUM_JOINTS_SOFT: 4
    RAW_IMAGE_SIZE:
    - 2400
    - 1935
    ROOT: /home/jingyu/Projects/python/vscode/Jingyu/Landmark/secondCeph/data/ISBI2015/
    SIGMA: 3
    SOFT_INDICES:
    - 12
    - 13
    - 14
    - 15
    TEST:
      IMG_PREFIX: RawImage/Test2Data
    TRAIN:
      AUG:
        ROT_FACTOR: 30
        SCALE_FACTOR: 0.3
        SHIFT_FACTOR:
        - 0.15
        - 0.15
      IMG_PREFIX: RawImage/TrainingData
    VAL:
      IMG_PREFIX: RawImage/Test1Data
  TYPE: Dataset_ISBI
LOSS:
  BASENUMBER: 20
  MASK_TYPE: pow
  TYPE: RLELossWithBasis
  RESIDUAL: true
MODEL:
  HIDDEN_LIST: -1
  IN_CHANNELS: 3
  NUM_LAYERS: 50
  PRETRAINED: ''
  PRETRAINED_RIGHT: true
  TRY_LOAD: ''
  TYPE: HeatmapBasisNFR
  NUM_FC_FILTERS: [512, 256]
  NUM_BASES: 1
  
TRAIN:
  BATCH_SIZE: 8
  BEGIN_EPOCH: 0
  END_EPOCH: 300
  GRAD_CLIP:
    ENABLED: true
    MAX_NORM: 1
    NORM_TYPE: 2
  LR: 0.0004
  LR_SCHEDULE:
    END_FACTOR: 0.01
    TYPE: linearLR
    T_MAX: 300
  OPTIMIZER: adam
  WORLD_SIZE: 2
VALIDATE:
  RADII:
  - 2.0
  - 2.5
  - 3.0
  - 4.0
  SHOWNORM: minmaxNorm
